/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as AboutRouteImport } from "./routes/about";
import { Route as AttributionRouteImport } from "./routes/attribution";
import { Route as BookmarksRouteImport } from "./routes/bookmarks";
import { Route as HistoryRouteImport } from "./routes/history";
import { Route as ReferenceRouteImport } from "./routes/reference";
import { Route as SentencePracticeRouteImport } from "./routes/sentence-practice";
import { Route as FolderFileRouteImport } from "./routes/folder/file";

const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const AboutRoute = AboutRouteImport.update({
  id: "/about",
  path: "/about",
  getParentRoute: () => rootRouteImport,
} as any);
const AttributionRoute = AttributionRouteImport.update({
  id: "/attribution",
  path: "/attribution",
  getParentRoute: () => rootRouteImport,
} as any);
const BookmarksRoute = BookmarksRouteImport.update({
  id: "/bookmarks",
  path: "/bookmarks",
  getParentRoute: () => rootRouteImport,
} as any);
const HistoryRoute = HistoryRouteImport.update({
  id: "/history",
  path: "/history",
  getParentRoute: () => rootRouteImport,
} as any);
const ReferenceRoute = ReferenceRouteImport.update({
  id: "/reference",
  path: "/reference",
  getParentRoute: () => rootRouteImport,
} as any);
const SentencePracticeRoute = SentencePracticeRouteImport.update({
  id: "/sentence-practice",
  path: "/sentence-practice",
  getParentRoute: () => rootRouteImport,
} as any);
const FolderFileRoute = FolderFileRouteImport.update({
  id: "/folder/file",
  path: "/folder/file",
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/about": typeof AboutRoute;
  "/attribution": typeof AttributionRoute;
  "/bookmarks": typeof BookmarksRoute;
  "/history": typeof HistoryRoute;
  "/reference": typeof ReferenceRoute;
  "/sentence-practice": typeof SentencePracticeRoute;
  "/folder/file": typeof FolderFileRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/about": typeof AboutRoute;
  "/attribution": typeof AttributionRoute;
  "/bookmarks": typeof BookmarksRoute;
  "/history": typeof HistoryRoute;
  "/reference": typeof ReferenceRoute;
  "/sentence-practice": typeof SentencePracticeRoute;
  "/folder/file": typeof FolderFileRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/about": typeof AboutRoute;
  "/attribution": typeof AttributionRoute;
  "/bookmarks": typeof BookmarksRoute;
  "/history": typeof HistoryRoute;
  "/reference": typeof ReferenceRoute;
  "/sentence-practice": typeof SentencePracticeRoute;
  "/folder/file": typeof FolderFileRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/about"
    | "/attribution"
    | "/bookmarks"
    | "/history"
    | "/reference"
    | "/sentence-practice"
    | "/folder/file";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/about"
    | "/attribution"
    | "/bookmarks"
    | "/history"
    | "/reference"
    | "/sentence-practice"
    | "/folder/file";
  id:
    | "__root__"
    | "/"
    | "/about"
    | "/attribution"
    | "/bookmarks"
    | "/history"
    | "/reference"
    | "/sentence-practice"
    | "/folder/file";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  AboutRoute: typeof AboutRoute;
  AttributionRoute: typeof AttributionRoute;
  BookmarksRoute: typeof BookmarksRoute;
  HistoryRoute: typeof HistoryRoute;
  ReferenceRoute: typeof ReferenceRoute;
  SentencePracticeRoute: typeof SentencePracticeRoute;
  FolderFileRoute: typeof FolderFileRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/about": {
      id: "/about";
      path: "/about";
      fullPath: "/about";
      preLoaderRoute: typeof AboutRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/attribution": {
      id: "/attribution";
      path: "/attribution";
      fullPath: "/attribution";
      preLoaderRoute: typeof AttributionRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/bookmarks": {
      id: "/bookmarks";
      path: "/bookmarks";
      fullPath: "/bookmarks";
      preLoaderRoute: typeof BookmarksRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/history": {
      id: "/history";
      path: "/history";
      fullPath: "/history";
      preLoaderRoute: typeof HistoryRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/reference": {
      id: "/reference";
      path: "/reference";
      fullPath: "/reference";
      preLoaderRoute: typeof ReferenceRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/sentence-practice": {
      id: "/sentence-practice";
      path: "/sentence-practice";
      fullPath: "/sentence-practice";
      preLoaderRoute: typeof SentencePracticeRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/folder/file": {
      id: "/folder/file";
      path: "/folder/file";
      fullPath: "/folder/file";
      preLoaderRoute: typeof FolderFileRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AttributionRoute: AttributionRoute,
  BookmarksRoute: BookmarksRoute,
  HistoryRoute: HistoryRoute,
  ReferenceRoute: ReferenceRoute,
  SentencePracticeRoute: SentencePracticeRoute,
  FolderFileRoute: FolderFileRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
