// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: created_sentences.sql

package database

import (
	"context"
	"database/sql"
)

const createCreatedSentence = `-- name: CreateCreatedSentence :one
INSERT INTO created_sentences
    (id, created_at, updated_at, japanese_text, english_meaning)
VALUES(
    gen_random_uuid(),
    NOW(),
    NOW(),
    $1,
    $2
)
RETURNING id, created_at, updated_at, japanese_text, english_meaning
`

type CreateCreatedSentenceParams struct {
	JapaneseText   sql.NullString
	EnglishMeaning sql.NullString
}

func (q *Queries) CreateCreatedSentence(ctx context.Context, arg CreateCreatedSentenceParams) (CreatedSentence, error) {
	row := q.db.QueryRowContext(ctx, createCreatedSentence, arg.JapaneseText, arg.EnglishMeaning)
	var i CreatedSentence
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.JapaneseText,
		&i.EnglishMeaning,
	)
	return i, err
}
