// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: created_sentences_vocabularies.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createCreatedSentencesVocabularies = `-- name: CreateCreatedSentencesVocabularies :one
INSERT INTO created_sentences_vocabularies(
    id,
    created_at,
    updated_at,
    created_sentence_id,
    vocabulary_id
)
VALUES(
    gen_random_uuid(),
    NOW(),
    NOW(),
    $1,
    $2
)
RETURNING id, created_at, updated_at, created_sentence_id, vocabulary_id
`

type CreateCreatedSentencesVocabulariesParams struct {
	CreatedSentenceID uuid.NullUUID
	VocabularyID      uuid.NullUUID
}

func (q *Queries) CreateCreatedSentencesVocabularies(ctx context.Context, arg CreateCreatedSentencesVocabulariesParams) (CreatedSentencesVocabulary, error) {
	row := q.db.QueryRowContext(ctx, createCreatedSentencesVocabularies, arg.CreatedSentenceID, arg.VocabularyID)
	var i CreatedSentencesVocabulary
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedSentenceID,
		&i.VocabularyID,
	)
	return i, err
}
