// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: created_sentences_grammar_concepts.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createCreatedSentencesGrammarConcepts = `-- name: CreateCreatedSentencesGrammarConcepts :one
INSERT INTO created_sentences_grammar_concepts(
    id,
    created_at,
    updated_at,
    created_sentence_id,
    grammar_concept_id
)
VALUES(
    gen_random_uuid(),
    NOW(),
    NOW(),
    $1,
    $2
)
RETURNING id, created_at, updated_at, created_sentence_id, grammar_concept_id
`

type CreateCreatedSentencesGrammarConceptsParams struct {
	CreatedSentenceID uuid.NullUUID
	GrammarConceptID  uuid.NullUUID
}

func (q *Queries) CreateCreatedSentencesGrammarConcepts(ctx context.Context, arg CreateCreatedSentencesGrammarConceptsParams) (CreatedSentencesGrammarConcept, error) {
	row := q.db.QueryRowContext(ctx, createCreatedSentencesGrammarConcepts, arg.CreatedSentenceID, arg.GrammarConceptID)
	var i CreatedSentencesGrammarConcept
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedSentenceID,
		&i.GrammarConceptID,
	)
	return i, err
}
