// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: example_sentences.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createExampleSentence = `-- name: CreateExampleSentence :one
INSERT INTO example_sentences
    (id, created_at, updated_at, japanese_text, english_meaning, grammar_concept_id)
VALUES(
    gen_random_uuid(),
    NOW(),
    NOW(),
    $1,
    $2,
    $3
)
RETURNING id, created_at, updated_at, japanese_text, english_meaning, grammar_concept_id
`

type CreateExampleSentenceParams struct {
	JapaneseText     sql.NullString
	EnglishMeaning   sql.NullString
	GrammarConceptID uuid.NullUUID
}

func (q *Queries) CreateExampleSentence(ctx context.Context, arg CreateExampleSentenceParams) (ExampleSentence, error) {
	row := q.db.QueryRowContext(ctx, createExampleSentence, arg.JapaneseText, arg.EnglishMeaning, arg.GrammarConceptID)
	var i ExampleSentence
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.JapaneseText,
		&i.EnglishMeaning,
		&i.GrammarConceptID,
	)
	return i, err
}

const getExampleSentenceWithGrammarConcept = `-- name: GetExampleSentenceWithGrammarConcept :one
SELECT
  es.id,
  es.created_at,
  es.updated_at,
  es.japanese_text,
  es.english_meaning,
  es.grammar_concept_id,

  gc.id AS grammar_concept_id,
  -- gc.created_at AS grammar_concept_created_at,
  -- gc.updated_at AS grammar_concept_updated_at,
  gc.concept AS grammar_concept,
  gc.definition AS grammar_definition
FROM example_sentences AS es
JOIN grammar_concepts AS gc
  ON gc.id = es.grammar_concept_id
WHERE es.id = $1
`

type GetExampleSentenceWithGrammarConceptRow struct {
	ID                 uuid.UUID
	CreatedAt          sql.NullTime
	UpdatedAt          sql.NullTime
	JapaneseText       sql.NullString
	EnglishMeaning     sql.NullString
	GrammarConceptID   uuid.NullUUID
	GrammarConceptID_2 uuid.UUID
	GrammarConcept     sql.NullString
	GrammarDefinition  sql.NullString
}

func (q *Queries) GetExampleSentenceWithGrammarConcept(ctx context.Context, id uuid.UUID) (GetExampleSentenceWithGrammarConceptRow, error) {
	row := q.db.QueryRowContext(ctx, getExampleSentenceWithGrammarConcept, id)
	var i GetExampleSentenceWithGrammarConceptRow
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.JapaneseText,
		&i.EnglishMeaning,
		&i.GrammarConceptID,
		&i.GrammarConceptID_2,
		&i.GrammarConcept,
		&i.GrammarDefinition,
	)
	return i, err
}
