// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: example_sentences.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createExampleSentence = `-- name: CreateExampleSentence :one
INSERT INTO example_sentences
    (id, created_at, updated_at, japanese_text, english_meaning, grammar_concept_id)
VALUES(
    gen_random_uuid(),
    NOW(),
    NOW(),
    $1,
    $2,
    $3
)
RETURNING id, created_at, updated_at, japanese_text, english_meaning, grammar_concept_id
`

type CreateExampleSentenceParams struct {
	JapaneseText     sql.NullString
	EnglishMeaning   sql.NullString
	GrammarConceptID uuid.NullUUID
}

func (q *Queries) CreateExampleSentence(ctx context.Context, arg CreateExampleSentenceParams) (ExampleSentence, error) {
	row := q.db.QueryRowContext(ctx, createExampleSentence, arg.JapaneseText, arg.EnglishMeaning, arg.GrammarConceptID)
	var i ExampleSentence
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.JapaneseText,
		&i.EnglishMeaning,
		&i.GrammarConceptID,
	)
	return i, err
}

const getExampleSentenceWithGrammarConcept = `-- name: GetExampleSentenceWithGrammarConcept :one
SELECT
  es.id,
  es.created_at,
  es.updated_at,
  es.japanese_text,
  es.english_meaning,
  es.grammar_concept_id,

  gc.id AS grammar_concept_id,
  -- gc.created_at AS grammar_concept_created_at,
  -- gc.updated_at AS grammar_concept_updated_at,
  gc.jlpt_level AS grammar_concept_jlpt_level,
  gc.concept AS grammar_concept,
  gc.definition AS grammar_definition
FROM example_sentences AS es
JOIN grammar_concepts AS gc
  ON gc.id = es.grammar_concept_id
WHERE es.id = $1
`

type GetExampleSentenceWithGrammarConceptRow struct {
	ID                      uuid.UUID
	CreatedAt               sql.NullTime
	UpdatedAt               sql.NullTime
	JapaneseText            sql.NullString
	EnglishMeaning          sql.NullString
	GrammarConceptID        uuid.NullUUID
	GrammarConceptID_2      uuid.UUID
	GrammarConceptJlptLevel NullJlptLevelEnum
	GrammarConcept          sql.NullString
	GrammarDefinition       sql.NullString
}

func (q *Queries) GetExampleSentenceWithGrammarConcept(ctx context.Context, id uuid.UUID) (GetExampleSentenceWithGrammarConceptRow, error) {
	row := q.db.QueryRowContext(ctx, getExampleSentenceWithGrammarConcept, id)
	var i GetExampleSentenceWithGrammarConceptRow
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.JapaneseText,
		&i.EnglishMeaning,
		&i.GrammarConceptID,
		&i.GrammarConceptID_2,
		&i.GrammarConceptJlptLevel,
		&i.GrammarConcept,
		&i.GrammarDefinition,
	)
	return i, err
}

const getExampleSentencesByGrammarConceptId = `-- name: GetExampleSentencesByGrammarConceptId :many
SELECT
    id,
    created_at,
    updated_at,
    japanese_text,
    english_meaning,
    grammar_concept_id
FROM example_sentences
WHERE grammar_concept_id = $1
ORDER BY created_at, id
`

func (q *Queries) GetExampleSentencesByGrammarConceptId(ctx context.Context, grammarConceptID uuid.NullUUID) ([]ExampleSentence, error) {
	rows, err := q.db.QueryContext(ctx, getExampleSentencesByGrammarConceptId, grammarConceptID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExampleSentence
	for rows.Next() {
		var i ExampleSentence
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.JapaneseText,
			&i.EnglishMeaning,
			&i.GrammarConceptID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateExampleSentenceById = `-- name: UpdateExampleSentenceById :one
UPDATE example_sentences
SET
    updated_at = NOW(),
    japanese_text = COALESCE($1, japanese_text),
    english_meaning = COALESCE($2, english_meaning),
    grammar_concept_id = COALESCE($3, grammar_concept_id)
WHERE
    id=$4
RETURNING id, created_at, updated_at, japanese_text, english_meaning, grammar_concept_id
`

type UpdateExampleSentenceByIdParams struct {
	JapaneseText     sql.NullString
	EnglishMeaning   sql.NullString
	GrammarConceptID uuid.NullUUID
	ID               uuid.UUID
}

func (q *Queries) UpdateExampleSentenceById(ctx context.Context, arg UpdateExampleSentenceByIdParams) (ExampleSentence, error) {
	row := q.db.QueryRowContext(ctx, updateExampleSentenceById,
		arg.JapaneseText,
		arg.EnglishMeaning,
		arg.GrammarConceptID,
		arg.ID,
	)
	var i ExampleSentence
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.JapaneseText,
		&i.EnglishMeaning,
		&i.GrammarConceptID,
	)
	return i, err
}
