// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: grammar_concepts.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createGrammarConcept = `-- name: CreateGrammarConcept :one
INSERT INTO grammar_concepts
    (id, created_at, updated_at, jlpt_level, concept, definition)
VALUES(
    gen_random_uuid(),
    NOW(),
    NOW(),
    $1,
    $2,
    $3
)
RETURNING id, created_at, updated_at, jlpt_level, concept, definition
`

type CreateGrammarConceptParams struct {
	JlptLevel  NullJlptLevelEnum
	Concept    sql.NullString
	Definition sql.NullString
}

func (q *Queries) CreateGrammarConcept(ctx context.Context, arg CreateGrammarConceptParams) (GrammarConcept, error) {
	row := q.db.QueryRowContext(ctx, createGrammarConcept, arg.JlptLevel, arg.Concept, arg.Definition)
	var i GrammarConcept
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.JlptLevel,
		&i.Concept,
		&i.Definition,
	)
	return i, err
}

const getGrammarConceptById = `-- name: GetGrammarConceptById :one
SELECT id, created_at, updated_at, jlpt_level, concept, definition FROM grammar_concepts WHERE id=$1
`

func (q *Queries) GetGrammarConceptById(ctx context.Context, id uuid.UUID) (GrammarConcept, error) {
	row := q.db.QueryRowContext(ctx, getGrammarConceptById, id)
	var i GrammarConcept
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.JlptLevel,
		&i.Concept,
		&i.Definition,
	)
	return i, err
}

const updateGrammarConceptById = `-- name: UpdateGrammarConceptById :one
UPDATE grammar_concepts
SET
    updated_at = NOW(),
    jlpt_level = COALESCE($1, jlpt_level),
    concept = COALESCE($2, concept),
    definition = COALESCE($3, definition)
WHERE
    id=$4
RETURNING id, created_at, updated_at, jlpt_level, concept, definition
`

type UpdateGrammarConceptByIdParams struct {
	JlptLevel  NullJlptLevelEnum
	Concept    sql.NullString
	Definition sql.NullString
	ID         uuid.UUID
}

func (q *Queries) UpdateGrammarConceptById(ctx context.Context, arg UpdateGrammarConceptByIdParams) (GrammarConcept, error) {
	row := q.db.QueryRowContext(ctx, updateGrammarConceptById,
		arg.JlptLevel,
		arg.Concept,
		arg.Definition,
		arg.ID,
	)
	var i GrammarConcept
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.JlptLevel,
		&i.Concept,
		&i.Definition,
	)
	return i, err
}
