// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: grammar_concepts.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createGrammarConcept = `-- name: CreateGrammarConcept :one
INSERT INTO grammar_concepts
    (id, created_at, updated_at, jlpt_level, concept, definition)
VALUES(
    gen_random_uuid(),
    NOW(),
    NOW(),
    $1,
    $2,
    $3
)
RETURNING id, created_at, updated_at, jlpt_level, concept, definition
`

type CreateGrammarConceptParams struct {
	JlptLevel  NullJlptLevelEnum
	Concept    sql.NullString
	Definition sql.NullString
}

func (q *Queries) CreateGrammarConcept(ctx context.Context, arg CreateGrammarConceptParams) (GrammarConcept, error) {
	row := q.db.QueryRowContext(ctx, createGrammarConcept, arg.JlptLevel, arg.Concept, arg.Definition)
	var i GrammarConcept
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.JlptLevel,
		&i.Concept,
		&i.Definition,
	)
	return i, err
}

const getGrammarConceptById = `-- name: GetGrammarConceptById :one
SELECT id, created_at, updated_at, jlpt_level, concept, definition
FROM grammar_concepts
WHERE id=$1
`

func (q *Queries) GetGrammarConceptById(ctx context.Context, id uuid.UUID) (GrammarConcept, error) {
	row := q.db.QueryRowContext(ctx, getGrammarConceptById, id)
	var i GrammarConcept
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.JlptLevel,
		&i.Concept,
		&i.Definition,
	)
	return i, err
}

const getRandomGrammarConcepts = `-- name: GetRandomGrammarConcepts :many
WITH selected_concepts AS (
    SELECT
        gc.id,
        gc.created_at,
        gc.updated_at,
        gc.jlpt_level,
        gc.concept,
        gc.definition
    FROM grammar_concepts AS gc
    ORDER BY RANDOM()
    LIMIT $1
)
SELECT
    sc.id,
    sc.created_at,
    sc.updated_at,
    sc.jlpt_level,
    sc.concept,
    sc.definition,
    es.id AS example_sentence_id,
    es.japanese_text AS example_sentence_japanese_text,
    es.english_meaning AS example_sentence_english_text
FROM selected_concepts AS sc
LEFT JOIN example_sentences AS es
    ON sc.id = es.grammar_concept_id
`

type GetRandomGrammarConceptsRow struct {
	ID                          uuid.UUID
	CreatedAt                   sql.NullTime
	UpdatedAt                   sql.NullTime
	JlptLevel                   NullJlptLevelEnum
	Concept                     sql.NullString
	Definition                  sql.NullString
	ExampleSentenceID           uuid.NullUUID
	ExampleSentenceJapaneseText sql.NullString
	ExampleSentenceEnglishText  sql.NullString
}

func (q *Queries) GetRandomGrammarConcepts(ctx context.Context, limit int32) ([]GetRandomGrammarConceptsRow, error) {
	rows, err := q.db.QueryContext(ctx, getRandomGrammarConcepts, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRandomGrammarConceptsRow
	for rows.Next() {
		var i GetRandomGrammarConceptsRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.JlptLevel,
			&i.Concept,
			&i.Definition,
			&i.ExampleSentenceID,
			&i.ExampleSentenceJapaneseText,
			&i.ExampleSentenceEnglishText,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateGrammarConceptById = `-- name: UpdateGrammarConceptById :one
UPDATE grammar_concepts
SET
    updated_at = NOW(),
    jlpt_level = COALESCE($1, jlpt_level),
    concept = COALESCE($2, concept),
    definition = COALESCE($3, definition)
WHERE
    id=$4
RETURNING id, created_at, updated_at, jlpt_level, concept, definition
`

type UpdateGrammarConceptByIdParams struct {
	JlptLevel  NullJlptLevelEnum
	Concept    sql.NullString
	Definition sql.NullString
	ID         uuid.UUID
}

func (q *Queries) UpdateGrammarConceptById(ctx context.Context, arg UpdateGrammarConceptByIdParams) (GrammarConcept, error) {
	row := q.db.QueryRowContext(ctx, updateGrammarConceptById,
		arg.JlptLevel,
		arg.Concept,
		arg.Definition,
		arg.ID,
	)
	var i GrammarConcept
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.JlptLevel,
		&i.Concept,
		&i.Definition,
	)
	return i, err
}
