// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"database/sql"

	"github.com/google/uuid"
)

type ExampleSentence struct {
	ID               uuid.UUID
	CreatedAt        sql.NullTime
	UpdatedAt        sql.NullTime
	JapaneseText     sql.NullString
	EnglishMeaning   sql.NullString
	GrammarConceptID uuid.NullUUID
}

type GrammarConcept struct {
	ID         uuid.UUID
	CreatedAt  sql.NullTime
	UpdatedAt  sql.NullTime
	Concept    sql.NullString
	Definition sql.NullString
}

type Vocabulary struct {
	ID             uuid.UUID
	CreatedAt      sql.NullTime
	UpdatedAt      sql.NullTime
	WikiIndex      sql.NullInt32
	Kana           sql.NullString
	Kanji          sql.NullString
	Classification []string
	Definition     sql.NullString
}
