// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: vocabularies.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const createVocabulary = `-- name: CreateVocabulary :one
INSERT INTO vocabularies
    (id, created_at, updated_at, jlpt_level, wiki_index, kana, kanji, classification, definition)
VALUES(
    gen_random_uuid(),
    NOW(),
    NOW(),
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
RETURNING id, created_at, updated_at, jlpt_level, wiki_index, kana, kanji, classification, definition
`

type CreateVocabularyParams struct {
	JlptLevel      NullJlptLevelEnum
	WikiIndex      sql.NullInt32
	Kana           sql.NullString
	Kanji          sql.NullString
	Classification []string
	Definition     sql.NullString
}

func (q *Queries) CreateVocabulary(ctx context.Context, arg CreateVocabularyParams) (Vocabulary, error) {
	row := q.db.QueryRowContext(ctx, createVocabulary,
		arg.JlptLevel,
		arg.WikiIndex,
		arg.Kana,
		arg.Kanji,
		pq.Array(arg.Classification),
		arg.Definition,
	)
	var i Vocabulary
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.JlptLevel,
		&i.WikiIndex,
		&i.Kana,
		&i.Kanji,
		pq.Array(&i.Classification),
		&i.Definition,
	)
	return i, err
}

const getRandomVocabularies = `-- name: GetRandomVocabularies :many
SELECT id, created_at, updated_at, jlpt_level, wiki_index, kana, kanji, classification, definition
FROM vocabularies
ORDER BY RANDOM()
LIMIT $1
`

func (q *Queries) GetRandomVocabularies(ctx context.Context, limit int32) ([]Vocabulary, error) {
	rows, err := q.db.QueryContext(ctx, getRandomVocabularies, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Vocabulary
	for rows.Next() {
		var i Vocabulary
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.JlptLevel,
			&i.WikiIndex,
			&i.Kana,
			&i.Kanji,
			pq.Array(&i.Classification),
			&i.Definition,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getVocabularyById = `-- name: GetVocabularyById :one
SELECT id, created_at, updated_at, jlpt_level, wiki_index, kana, kanji, classification, definition
FROM vocabularies
WHERE id=$1
`

func (q *Queries) GetVocabularyById(ctx context.Context, id uuid.UUID) (Vocabulary, error) {
	row := q.db.QueryRowContext(ctx, getVocabularyById, id)
	var i Vocabulary
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.JlptLevel,
		&i.WikiIndex,
		&i.Kana,
		&i.Kanji,
		pq.Array(&i.Classification),
		&i.Definition,
	)
	return i, err
}

const updateVocabularyById = `-- name: UpdateVocabularyById :one
UPDATE vocabularies
SET
    updated_at = NOW(),
    wiki_index = COALESCE($1, wiki_index),
    kana = COALESCE($2, kana),
    kanji = COALESCE($3, kanji),
    classification = COALESCE($4, classification),
    definition = COALESCE($5, definition)
WHERE
    id=$6
RETURNING id, created_at, updated_at, jlpt_level, wiki_index, kana, kanji, classification, definition
`

type UpdateVocabularyByIdParams struct {
	WikiIndex      sql.NullInt32
	Kana           sql.NullString
	Kanji          sql.NullString
	Classification []string
	Definition     sql.NullString
	ID             uuid.UUID
}

// TODO: This is missing JLPT level
func (q *Queries) UpdateVocabularyById(ctx context.Context, arg UpdateVocabularyByIdParams) (Vocabulary, error) {
	row := q.db.QueryRowContext(ctx, updateVocabularyById,
		arg.WikiIndex,
		arg.Kana,
		arg.Kanji,
		pq.Array(arg.Classification),
		arg.Definition,
		arg.ID,
	)
	var i Vocabulary
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.JlptLevel,
		&i.WikiIndex,
		&i.Kana,
		&i.Kanji,
		pq.Array(&i.Classification),
		&i.Definition,
	)
	return i, err
}
