# ===== Image build =====
FROM alpine AS base
RUN apk add --no-cache \
        ca-certificates \
        curl \
        go \
    && update-ca-certificates
RUN curl -LsSf https://astral.sh/uv/install.sh | sh
ENV PATH="/root/.local/bin:${PATH}"

WORKDIR /tsukuru
COPY ./uv.lock ./
COPY ./pyproject.toml ./
COPY ./.python-version ./
COPY ./apps-uv/kezuru/ ./apps-uv/kezuru/
COPY ./apps-go/jisho/ ./apps-go/jisho/
COPY ./scripts/ ./scripts/
COPY ./data/ ./data/
RUN uv sync --all-packages

WORKDIR /tsukuru/apps-go/jisho
RUN mkdir -p ./bin/server
RUN go build -o ./bin/server/app ./cmd/server
RUN mkdir -p ./bin/exec/importer
RUN go build -o ./bin/exec/importer/app ./cmd/exec/importer


# ===== Resusable Jisho container ====
FROM base AS jisho
RUN apk add --no-cache \
        ca-certificates \
    && update-ca-certificates
# installing goose form via `go install` consumes more space
RUN curl -fsSL \
    https://raw.githubusercontent.com/pressly/goose/master/install.sh |\
    sh
RUN chmod +x /usr/local/bin/goose

CMD ["./bin/server/app"]


# ===== Vite-Plus image for isolated Kami build-step =====
FROM ghcr.io/voidzero-dev/vite-plus:latest AS kami-build
WORKDIR /tsukuru
COPY --chown=vp:vp ./package.json ./
COPY --chown=vp:vp ./pnpm-lock.yaml ./
COPY --chown=vp:vp ./pnpm-workspace.yaml ./
COPY --chown=vp:vp ./apps-ts/kami ./apps-ts/kami
COPY --chown=vp:vp package.json pnpm-lock.yaml pnpm-workspace.yaml .node-version* ./
RUN pnpm approve-builds --all
RUN vp install --frozen-lockfile
WORKDIR /tsukuru/apps-ts/kami
RUN vp build --mode self-host


# ===== Nginx Kami runtime =====
FROM nginx:alpine AS kami-runtime
# Assuming npm run build outputs to /tsukuru/apps-ts/kami/dist/
COPY --from=kami-build \
    /tsukuru/apps-ts/kami/dist \
    /usr/share/nginx/html
COPY nginx.self-hosted.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
