server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    # These work by rerouting internal traffic that hit /self-host/[...] to the external endpoint
    # The vite-plus build-step currently hardcodes /self-host/ as a target endpoint
    location /self-host/api/ {
        proxy_pass http://jisho:8081/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /self-host/tsukuru/ {
        proxy_pass http://jisho:8081/tsukuru/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # Allows direct access to different paths (ex. /about) even if such pages
    #   exist as part of the JavaScript logic rather than plain HTML files that
    #   can be served.
    location / {
        try_files $uri $uri/ /index.html;
    }
}
