[project]
name = "tsukuru"
version = "0.5.1"
description = "vocabulary and concept randomizer for Japanese sentence construction review"
readme = "README.md"
requires-python = ">=3.14"
dependencies = ["python-dotenv>=1.2.3"]

[tool.uv]
exclude-newer = "1 week"

[tool.uv.sources]
kezuru = { workspace = true }

[tool.uv.workspace]
members = ["apps-uv/*"]
