[project]
name = "kezuru"
version = "1.2.2"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "beautifulsoup4>=4.14.3",
    "html5lib>=1.1",
    "requests>=2.33.1",
    "rich>=15.0.0",
]

[tool.uv]
exclude-newer = "1 week"

[build-system]
requires = ["setuptools>=75"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
include = ["lang_component*", "utils*"]
